"""
Renders the reporting module's ClassReportResponse/AssignmentReportResponse
to PDF bytes — same reportlab platypus approach and visual language as
report_pdf_service.py (Helvetica-only, no font files), kept as its own
small style block rather than importing report_pdf_service's private
helpers, since the two reports serve different audiences (an instructor
or admin reading about a roster, not a learner reading about themselves).
"""

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.schemas.reporting import AssignmentReportResponse, ClassReportResponse

EM_DASH = "—"

_HEADER_BG = colors.HexColor("#f0f0f0")
_GRID_COLOR = colors.HexColor("#dddddd")
_STRIPE_COLOR = colors.HexColor("#fafafa")
_OVERDUE_BG = colors.HexColor("#fdecea")

_TABLE_HEADER_STYLE = [
    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
    ("FONTSIZE", (0, 0), (-1, -1), 9),
    ("BACKGROUND", (0, 0), (-1, 0), _HEADER_BG),
    ("GRID", (0, 0), (-1, -1), 0.5, _GRID_COLOR),
    ("TOPPADDING", (0, 0), (-1, -1), 4),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
]


def _format_percent(value) -> str:
    return f"{value}%" if value is not None else EM_DASH


def _scope_title(scope: str) -> str:
    return "Platform-Wide" if scope == "platform" else "Class"


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "ReportTitle", parent=base["Title"], fontName="Helvetica-Bold", fontSize=18, spaceAfter=4
        ),
        "subtitle": ParagraphStyle(
            "ReportSubtitle", parent=base["Normal"], fontName="Helvetica", fontSize=10, textColor=colors.grey
        ),
        "heading": ParagraphStyle(
            "SectionHeading", parent=base["Heading2"], fontName="Helvetica-Bold", fontSize=13,
            spaceBefore=18, spaceAfter=6,
        ),
        "body": ParagraphStyle("Body", parent=base["Normal"], fontName="Helvetica", fontSize=10, leading=14),
        "cell": ParagraphStyle("Cell", parent=base["Normal"], fontName="Helvetica", fontSize=9, leading=12),
    }


def render_class_report_pdf(report: ClassReportResponse, generated_by: str) -> bytes:
    styles = _styles()
    buffer = BytesIO()
    title_text = f"{_scope_title(report.scope)} Report"
    doc = SimpleDocTemplate(
        buffer, pagesize=letter,
        topMargin=0.6 * inch, bottomMargin=0.6 * inch, leftMargin=0.6 * inch, rightMargin=0.6 * inch,
        title=title_text,
    )
    story = []

    story.append(Paragraph(title_text, styles["title"]))
    story.append(
        Paragraph(
            f"Generated by {generated_by} &nbsp;&middot;&nbsp; "
            f"{report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}",
            styles["subtitle"],
        )
    )
    story.append(Spacer(1, 0.25 * inch))

    summary_header = ["Learners", "Have practiced", "Avg. accuracy", "Open assignments", "Completed"]
    summary_values = [
        str(report.learner_count),
        str(report.active_learner_count),
        _format_percent(report.average_accuracy_percent),
        str(report.outstanding_assignment_count),
        str(report.completed_assignment_count),
    ]
    summary_table = Table([summary_header, summary_values], colWidths=[1.32 * inch] * 5)
    summary_table.setStyle(
        TableStyle(_TABLE_HEADER_STYLE + [
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTSIZE", (0, 1), (-1, 1), 13),
            ("TOPPADDING", (0, 1), (-1, 1), 8),
            ("BOTTOMPADDING", (0, 1), (-1, 1), 8),
        ])
    )
    story.append(summary_table)
    story.append(Spacer(1, 0.3 * inch))

    story.append(Paragraph("Most common weak letters", styles["heading"]))
    if report.weak_letter_distribution:
        weak_text = ", ".join(
            f"{w.letter} ({w.learner_count} learner{'s' if w.learner_count != 1 else ''})"
            for w in report.weak_letter_distribution
        )
        story.append(Paragraph(weak_text, styles["body"]))
    else:
        story.append(Paragraph("No weak areas identified across this group yet.", styles["body"]))
    story.append(Spacer(1, 0.3 * inch))

    story.append(Paragraph("Roster", styles["heading"]))
    if report.roster:
        roster_rows = [["Name", "Email", "Attempts", "Accuracy"]]
        for entry in report.roster:
            roster_rows.append([
                entry.name, entry.email, str(entry.total_attempts),
                _format_percent(entry.overall_accuracy_percent),
            ])
        roster_table = Table(roster_rows, colWidths=[1.6 * inch, 2.4 * inch, 0.9 * inch, 1.0 * inch], repeatRows=1)
        roster_table.setStyle(
            TableStyle(_TABLE_HEADER_STYLE + [
                ("ALIGN", (2, 0), (-1, -1), "CENTER"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, _STRIPE_COLOR]),
            ])
        )
        story.append(roster_table)
    else:
        story.append(Paragraph("No learners in this group yet.", styles["body"]))

    doc.build(story)
    return buffer.getvalue()


def render_assignment_report_pdf(report: AssignmentReportResponse, generated_by: str) -> bytes:
    styles = _styles()
    buffer = BytesIO()
    title_text = f"{_scope_title(report.scope)} Assignment Report"
    doc = SimpleDocTemplate(
        buffer, pagesize=letter,
        topMargin=0.6 * inch, bottomMargin=0.6 * inch, leftMargin=0.6 * inch, rightMargin=0.6 * inch,
        title=title_text,
    )
    story = []

    story.append(Paragraph(title_text, styles["title"]))
    story.append(
        Paragraph(
            f"Generated by {generated_by} &nbsp;&middot;&nbsp; "
            f"{report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}",
            styles["subtitle"],
        )
    )
    story.append(Spacer(1, 0.25 * inch))

    summary_header = ["Total assignments", "Completed", "Outstanding", "Overdue"]
    summary_values = [
        str(report.total_count), str(report.completed_count),
        str(report.outstanding_count), str(report.overdue_count),
    ]
    summary_table = Table([summary_header, summary_values], colWidths=[1.6 * inch] * 4)
    summary_table.setStyle(
        TableStyle(_TABLE_HEADER_STYLE + [
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTSIZE", (0, 1), (-1, 1), 14),
            ("TOPPADDING", (0, 1), (-1, 1), 8),
            ("BOTTOMPADDING", (0, 1), (-1, 1), 8),
        ])
    )
    story.append(summary_table)
    story.append(Spacer(1, 0.3 * inch))

    story.append(Paragraph("Assignments", styles["heading"]))
    if report.rows:
        rows = [["Learner", "Topic", "Due", "Status"]]
        row_styles = []
        for i, row in enumerate(report.rows, start=1):
            if row.completed:
                status = "Completed"
            elif row.overdue:
                status = "Overdue"
            else:
                status = "Open"
            rows.append([row.learner_name, row.topic, row.due_date or EM_DASH, status])
            if row.overdue:
                row_styles.append(("BACKGROUND", (0, i), (-1, i), _OVERDUE_BG))
        assignment_table = Table(rows, colWidths=[1.6 * inch, 1.8 * inch, 1.0 * inch, 1.5 * inch], repeatRows=1)
        assignment_table.setStyle(
            TableStyle(_TABLE_HEADER_STYLE + [
                ("ALIGN", (2, 0), (-1, -1), "CENTER"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, _STRIPE_COLOR]),
            ] + row_styles)
        )
        story.append(assignment_table)
        story.append(Spacer(1, 0.15 * inch))
        story.append(Paragraph("Rows shaded red are overdue: a due date in the past, not yet completed.", styles["body"]))
    else:
        story.append(Paragraph("No assignments in this group yet.", styles["body"]))

    doc.build(story)
    return buffer.getvalue()
